TeuToo/teutoo_front

- app/join/@location/(.)locationModal/page.tsx
- app/join/components/JoinForm.tsx
- app/join/components/KaKaoMap.tsx
- app/join/locationModal/page.tsx
- app/join/page.tsx
- app/join/zodJoinSchema.ts
- store/locationStore.ts
기존 
-  회원가입 페이지의 주소찾기 모달화면에서 새로고침시 빈화면으로 이동
변경
- 더 큰 지도화면으로 이동
> 회원가입 페이지의 주소찾기 모달화면에서 새로고침시 큰 지도 페이지로 이동

- app/introduceTrainer/components/IntroTrainerForm.tsx
- app/introduceTrainer/layout.tsx
- app/introduceTrainer/page.tsx
- app/introduceTrainer/zodTrainerSchema.ts
- app/join/components/JoinForm.tsx
- app/join/components/JoinInputFiled.tsx
- app/layout.tsx
- app/login/page.tsx
- components/formElement/TextArea.tsx
- components/formElement/TextField.tsx
트레이너 소개 페이지에대한 통신이 필요한 기능을 제외하고 디자인과 사진업로드기능, 유효성 검증기능 완성
> Introduce trainer 페이지 디자인 완성

- app/join/components/JoinForm.tsx
- app/join/components/JoinInputFiled.tsx
- app/join/components/KakaoMap.tsx
- app/join/components/LocationInputField.tsx
- app/join/lib/useSignup.ts
- app/join/zodJoinSchema.ts
- package-lock.json
- package.json
모달창을 열어 주소를 입력하고 해당주소상태를 모달을 닫았을때도 다른 컴포넌트에서 공유하려하였으나 공유가 되지않아 계속 회원가입 폼이 submit되지않는 이슈해결
> react hook form 버그픽스

- app/editInfo/components/EditInfoComponent.tsx
- app/introduceTrainer/components/IntroTrainerForm.tsx
- app/layout.tsx
- app/programManage/components/ProgramForm.tsx
- app/programManage/components/ProgramManageComponent.tsx
- app/programManage/layout.tsx
- app/programManage/page.tsx
- components/BGWhiteButton.tsx
- components/Header.tsx
- components/NumberButton.tsx
- components/PicturesElement.tsx
- components/formElement/TextArea.tsx
- components/formElement/TextField.tsx
1. 커밋실수로 커밋규칙 못지키고 한번에 커밋시켜버림(이해바람)
2. 프로그램 관리 페이지에서 횟수버튼은 ui변경이 필요하다고 생각되어 피그마에 반영하고 코드에도 반영함
> Program management 페이지 디자인완성

- app/editInfo/components/EditInfoComponent.tsx
- app/editInfo/layout.tsx
- app/editInfo/page.tsx
- app/introduceTrainer/components/IntroTrainerForm.tsx
- app/introduceTrainer/page.tsx
- app/join/@location/(.)locationModal/page.tsx
- app/join/components/JoinForm.tsx
- app/join/page.tsx
- app/layout.tsx
- app/programManage/components/ProgramForm.tsx
- app/programManage/components/ProgramManageComponent.tsx
- app/programManage/layout.tsx
- app/programManage/page.tsx
- app/trainerMyPage/layout.tsx
- app/trainerMyPage/page.tsx
- components/BottomNavigationBar.tsx
- components/Header.tsx
- components/formElement/TextField.tsx
1.  모바일 우선 개발이지만 데스크탑환경에서 화면이 과도하게 퍼지는현상 방지
2. 컴포넌트 재사용성강화
3. 같은컴포넌트가 여러번 렌더링되는 환경에서 key값 추가
4. 데스크탑환경에서 좌우 레터박스가 검은색이었던것을 수정
> 전체적인 디자인수정

- app/join/components/KakaoMap.tsx
- app/join/page.tsx
- app/layout.tsx
- app/programManage/components/ProgramForm.tsx
- app/programManage/components/ProgramManageComponent.tsx
- app/programManage/layout.tsx
- app/programManage/page.tsx
- app/schedule/components/DayContourLine.tsx
- app/schedule/components/DetailedSchedule.tsx
- app/schedule/components/ScheduleAtom.tsx
- app/schedule/components/ScheduleComponent.tsx
- app/schedule/layout.tsx
- app/schedule/page.tsx
- components/NumberButton.tsx
- window.d.ts
1. 기존 피그마 디자인에서 아쉬웠던 부분 개선
2. 날짜에따라 div하이라이팅되게 기능구현
3. 날짜를 구분하기위한 구분선 삽입
> 트레이너 스케줄 페이지 디자인완성

- app/estimateUser/components/EstimateAtom.tsx
> Design: 사소한 디자인수정

- app/(afterLogin)/editInfo/@editLocation/(.)locationModal/page.tsx
- app/(afterLogin)/editInfo/locationModal/page.tsx
- app/(afterLogin)/estimateUser/page.tsx
- app/(afterLogin)/introduceTrainer/components/IntroTrainerForm.tsx
- app/(afterLogin)/introduceTrainer/components/PictureExist.tsx
- app/(afterLogin)/programManage/api/useDeleteProgram.ts
- app/(afterLogin)/programManage/api/useEditProgram.ts
- app/(afterLogin)/programManage/api/useManageProgram.ts
- app/(afterLogin)/programManage/components/ProgramForm.tsx
- app/(afterLogin)/programManage/components/ProgramManageComponent.tsx
- app/(afterLogin)/programManage/components/TrainerProfile.tsx
- app/(afterLogin)/programManage/layout.tsx
- app/(afterLogin)/programManage/zodProgramSchema.ts
- app/(afterLogin)/trainerMyPage/components/MyInfoChunk.tsx
- components/NumberButton.tsx
1. 프로그램 삭제기능 구현
2. 프로그램 수정기능 구현
3. 프로그램 등록기능 구현
4. 다른 컴포넌트 재사용에 따른 유연성 강화
5. 마이페이지에서 이메일 렌더링기능
> 트레이너 프로그램 페이지 기능구현

- app/(afterLogin)/editInfo/components/EditInfoComponent.tsx
- app/(afterLogin)/editInfo/components/EditTextField.tsx
- app/(afterLogin)/editInfo/components/Picture.tsx
- app/immepassword/api/useImmePassword.ts
- app/immepassword/components/ImmePasswordForm.tsx
- app/immepassword/components/PWInputField.tsx
- app/immepassword/layout.tsx
- app/immepassword/page.tsx
- app/join/components/JoinForm.tsx
- app/join/components/JoinInputFiled.tsx
- app/login/components/LoginForm.tsx
- next.config.mjs
1. 비밀번호 분실시 임시비밀번호를 가입할때 작성했던 이메일로 전송할 수 있는 페이지 작성
2. s3 버킷 링크 이동으로인한 코드수정
3. 기존 사용자 정보 변경 시 비밀번호 수정기능 추가
> Feat: 비밀번호 분실시 임시비밀번호 발급페이지

- app/(afterLogin)/introduceTrainer/layout.tsx
- app/(afterLogin)/programManage/layout.tsx
- app/(afterLogin)/programManage/page.tsx
- app/(afterLogin)/trainerMyPage/components/MyInfoChunk.tsx
- app/login/components/LoginForm.tsx
- components/BottomNavigationBar.tsx
1. 트레이너 소개페이지 작성 => 프로그램 페이지 작성이기에 관련코드 작성
2. 하단 네비게이션바의 경로변경
3. 로그아웃 구현
> Feat: 정보작성 우선순위에 따른 코드작성

- app/(afterLogin)/programManage/api/fetchTrainerProgram.ts
- app/(afterLogin)/programManage/layout.tsx
> Fix: 배포실패로 인한 코드수정

- app/(afterLogin)/estimatePaper/components/EstimateFormTrainer.tsx
> Fix: 배포 실패로 인한 수정

- app/(afterLogin)/estimatePaper/components/EstimateFormUser.tsx
> Fix: 배포 실패로 인한 이슈해결

- app/(afterLogin)/estimate/@estimateTrainer/components/EstimateTrainerAtom.tsx
- app/(afterLogin)/estimate/@estimateTrainer/components/EstimateTrainerList.tsx
- app/(afterLogin)/estimate/@estimateTrainer/components/MyEstimateU.tsx
- app/(afterLogin)/estimate/@estimateUser/components/EstimateList.tsx
- app/(afterLogin)/estimate/@estimateUser/components/EstimateUserAtom.tsx
- app/(afterLogin)/estimate/@estimateUser/components/MyEstimateT.tsx
- app/(afterLogin)/estimate/@estimateUser/layout.tsx
- app/(afterLogin)/estimate/types/index.ts
> Fix: 서버측 제공 데이터구조 변경으로 인한 수정

- app/(afterLogin)/estimate/@estimateTrainer/components/EstimateTrainerAtom.tsx
- app/(afterLogin)/estimate/@estimateUser/components/EstimateModal.tsx
- app/(afterLogin)/estimate/@estimateUser/components/EstimateUserAtom.tsx
- app/(afterLogin)/estimate/@estimateUser/layout.tsx
- app/(afterLogin)/schedule/components/CalendarCompoenent.tsx
- app/(afterLogin)/schedule/components/DayScheduleList.tsx
- app/(afterLogin)/schedule/components/ScheduleAtom.tsx
- app/(afterLogin)/schedule/layout.tsx
- app/(afterLogin)/schedule/utils/formatDate.ts
- store/useDateStore.ts
1. 트레이너 스케줄 페이지에서 기존 mock데이터 => 서버측 데이터 
2. 채팅방 이동기능 추가
> Feat: 트레이너 스케줄 페이지 완성

- app/(afterLogin)/introduceTrainer/api/getTrainerIntro.ts
- app/(afterLogin)/introduceTrainer/layout.tsx
- app/(afterLogin)/programManage/layout.tsx
> Fix: 배포실패로 인한 수정

- app/layout.tsx
> Feat: 메타데이터 개선

- app/layout.tsx
> Fix: 메타데이터 이미지 경로수정

- app/(afterLogin)/editInfo/components/EditInfoComponent.tsx
- app/(afterLogin)/estimate/@estimateTrainer/components/EstimateTrainerList.tsx
- app/(afterLogin)/kakaoJoin/api/useKakaoJoin.ts
- app/(afterLogin)/kakaoJoin/components/ProfileImg.tsx
- app/(afterLogin)/kakaoJoin/layout.tsx
- app/(afterLogin)/kakaoJoin/page.tsx
- app/login/kakao/page.tsx
1. 소셜로그인 새로운회원일경우 추가 정보받는 페이지 제작
2. 프로필 이미지 컴포넌트 생성
> Feat: 소셜로그인 새로운회원일경우 추가 정보받는 페이지 제작

- app/(afterLogin)/myPage/@trainerMyPage/components/MyInfoChunk.tsx
> Fix: 로그아웃시 상태정리를 위한 새로고침

- app/(afterLogin)/kakaoJoin/page.tsx
> Feat: 첫 소셜회원가입 유저에게 추가적인 정보를 요구하는 alert

- app/trainer/[id]/_components/trainer-info.tsx
> Fix: 임시 프로필 사진 수정 및 Image 컴포넌트 필수 props 누락으로인한 문제해결

- app/(afterLogin)/editInfo/api/useEditInfo.ts
- app/(afterLogin)/editInfo/components/EditInfoComponent.tsx
- app/(afterLogin)/estimatePaper/@trainer/page.tsx
- app/(afterLogin)/estimatePaper/components/SelectProgram.tsx
- app/(afterLogin)/estimatePaper/layout.tsx
- app/(afterLogin)/programManage/components/ProgramManageComponent.tsx
- app/(afterLogin)/schedule/components/DayScheduleList.tsx
- app/(afterLogin)/schedule/layout.tsx
1. invalidate코드 작동하지않던것을 Tanstack query코드를 수정하여 해결
> Fix: Tanstack query 코드 수정

- app/(afterLogin)/schedule/api/getScheduleT.ts
- app/(afterLogin)/schedule/components/DayScheduleList.tsx
- app/(afterLogin)/schedule/layout.tsx
> Fix: api 코드 위치변경

- app/(afterLogin)/estimate/@estimateTrainer/components/EstimateTrainerList.tsx
- app/(afterLogin)/estimate/@estimateTrainer/components/MyEstimateU.tsx
- app/(afterLogin)/estimate/@estimateUser/components/EstimateModal.tsx
- app/(afterLogin)/estimate/@estimateUser/components/MyEstimateT.tsx
- app/(afterLogin)/estimate/api/getImmeEstimateU.ts
- app/(afterLogin)/estimate/api/getInfiniteEstimateU.ts
- app/(afterLogin)/estimate/api/getMtEstimateU.ts
- app/(afterLogin)/estimate/api/getMyEstimateT.ts
- app/(afterLogin)/estimate/api/getOneEstimateT.ts
- app/(afterLogin)/estimatePaper/@trainer/page.tsx
- app/(afterLogin)/estimatePaper/api/getOnlyTrainerPrograms.ts
- app/(afterLogin)/estimatePaper/components/SelectProgram.tsx
- app/(afterLogin)/programManage/components/ProgramManageComponent.tsx
> Refactor: api코드 분리

- app/(afterLogin)/estimate/@estimateUser/components/EstimateButton.tsx
- app/(afterLogin)/estimatePaper/api/useEditTrainer.ts
- app/(afterLogin)/estimatePaper/api/useEditUser.ts
- app/(afterLogin)/estimatePaper/api/useSubmitTrainer.ts
- app/(afterLogin)/estimatePaper/api/useSubmitUser.ts
- app/(afterLogin)/estimatePaper/components/EstimateFormTrainer.tsx
- app/(afterLogin)/introduceTrainer/api/useSetInfoTrainer.ts
- app/(afterLogin)/myPage/@trainerMyPage/components/MyInfoChunk.tsx
- app/(afterLogin)/myPage/@trainerMyPage/components/MyPageButton.tsx
- app/(afterLogin)/programManage/api/useEditProgram.ts
- app/(afterLogin)/programManage/api/useManageProgram.ts
- app/(afterLogin)/programManage/components/ProgramManageComponent.tsx
- app/(afterLogin)/programManage/layout.tsx
- app/(afterLogin)/programManage/page.tsx
- app/login/api/useLogin.ts
- components/LightButton.tsx
- components/SmallHeader.tsx
> Design: 디자인수정

- app/_components/trainer-list.tsx
- app/page.tsx
- app/program/[id]/page.tsx
- app/trainer/[id]/_components/trainer-info.tsx
- lib/hooks/useChatRoom.ts
트레이너 상세 페이지 백 버튼 수정, 레이아웃 수정
채팅 소켓 url 수정
트레이너 목록 페이지 무한 스크롤 버그 수정
> Fix: 버그 수정
